name: CI

on: [push, pull_request]

jobs:
  test:
    # YAML anchor for the runner OS
    runs-on: &runner-os [ubuntu-24.04]

    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .  # Install the deflicker package in editable mode

    - name: Run deflicker script inside Docker
      run: |
        python3 deflicker/__main__.py -h

        # Download some images, put them into a folder
        mkdir -p images
        curl -o images/image-112#1.jpg https://raw.githubusercontent.com/yavuzceliker/sample-images/refs/heads/main/docs/image-112[0-5].jpg

        # Run deflicker with various options
        python3 deflicker/__main__.py images
        python3 deflicker/__main__.py images -o output_images
        python3 deflicker/__main__.py images -w 2
        python3 deflicker/__main__.py images -f png
        python3 deflicker/__main__.py images -s 3.5

    - name: Run pytest inside Docker
      run: |
        pytest
