name: CI

on: [push, pull_request]

jobs:
  test:
    # YAML anchor for the runner OS
    runs-on: &runner-os [ubuntu-24.04]

    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        # python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run deflicker script inside Docker
      run: |
        python3 deflicker/__main__.py -h
        # Download some images, run deflicker on them
        curl -O https://www.python.org/static/img/python-logo.png
        curl -O https://www.python.org/static/community_logos/python-powered-w-100x40.png
        curl -O https://www.python.org/static/community_logos/python-powered-h-50x65.png
        mkdir python_images
        mv python-logo.png python_images/
        mv python-powered-w-100x40.png python_images/
        mv python-powered-h-50x65.png python_images/
        python3 deflicker/__main__.py -i python_images
        python3 deflicker/__main__.py -i python_images -o output_images
        python3 deflicker/__main__.py -i python_images -w 2
        python3 deflicker/__main__.py -i python_images -f png
        python3 deflicker/__main__.py -i python_images -s 3.5

    - name: Run pytest inside Docker
      run: |
        pytest
